/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'LAKINARA' at '9/12/16 11:58 AM' with Gradle 3.0
 *
 * @author LAKINARA, @date 9/12/16 11:58 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
